/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\deskTools\\blog\\vuepressdir\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-71d4f21d",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71d4f21d").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-37cfbc2d",
    path: "/share/hkgd/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37cfbc2d").then(next)
    },
  },
  {
    path: "/share/hkgd/index.html",
    redirect: "/share/hkgd/"
  },
  {
    name: "v-4a0a4881",
    path: "/share/nginx/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a0a4881").then(next)
    },
  },
  {
    path: "/share/nginx/index.html",
    redirect: "/share/nginx/"
  },
  {
    name: "v-b55f5c00",
    path: "/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b55f5c00").then(next)
    },
  },
  {
    path: "/web/index.html",
    redirect: "/web/"
  },
  {
    name: "v-3bd326aa",
    path: "/web/eu-fy/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bd326aa").then(next)
    },
  },
  {
    path: "/web/eu-fy/index.html",
    redirect: "/web/eu-fy/"
  },
  {
    name: "v-553db0ed",
    path: "/web/bw/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-553db0ed").then(next)
    },
  },
  {
    path: "/web/bw/index.html",
    redirect: "/web/bw/"
  },
  {
    name: "v-d07ca026",
    path: "/web/gd/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d07ca026").then(next)
    },
  },
  {
    path: "/web/gd/index.html",
    redirect: "/web/gd/"
  },
  {
    name: "v-5ce0132d",
    path: "/web/mnjx/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ce0132d").then(next)
    },
  },
  {
    path: "/web/mnjx/index.html",
    redirect: "/web/mnjx/"
  },
  {
    name: "v-2cf80ecd",
    path: "/web/tj/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2cf80ecd").then(next)
    },
  },
  {
    path: "/web/tj/index.html",
    redirect: "/web/tj/"
  },
  {
    name: "v-a0de9366",
    path: "/web/ydxy/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a0de9366").then(next)
    },
  },
  {
    path: "/web/ydxy/index.html",
    redirect: "/web/ydxy/"
  },
  {
    name: "v-4344d48d",
    path: "/web/ks/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4344d48d").then(next)
    },
  },
  {
    path: "/web/ks/index.html",
    redirect: "/web/ks/"
  },
  {
    name: "v-5e2c684d",
    path: "/web/xb/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e2c684d").then(next)
    },
  },
  {
    path: "/web/xb/index.html",
    redirect: "/web/xb/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]