/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "GY s 项目",
  "description": "开发记录",
  "base": "/web-about-me/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/web-about-me/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-71d4f21d",
      "path": "/",
      "lastUpdated": "3/22/2023, 3:57:23 PM",
      "lastUpdatedTimestamp": 1679471843000
    },
    {
      "frontmatter": {},
      "regularPath": "/web/",
      "relativePath": "web/README.md",
      "key": "v-b55f5c00",
      "path": "/web/"
    },
    {
      "frontmatter": {},
      "regularPath": "/web/eu-fy/",
      "relativePath": "web/eu-fy/README.md",
      "key": "v-3bd326aa",
      "path": "/web/eu-fy/",
      "headers": [
        {
          "level": 2,
          "title": "成航辅营管理端",
          "slug": "成航辅营管理端"
        },
        {
          "level": 2,
          "title": "项目技术",
          "slug": "项目技术"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/web/mnjx/",
      "relativePath": "web/mnjx/README.md",
      "key": "v-5ce0132d",
      "path": "/web/mnjx/",
      "headers": [
        {
          "level": 2,
          "title": "模拟教学",
          "slug": "模拟教学"
        },
        {
          "level": 2,
          "title": "模拟教学管理端",
          "slug": "模拟教学管理端"
        },
        {
          "level": 2,
          "title": "项目技术",
          "slug": "项目技术"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/web/bw/",
      "relativePath": "web/bw/README.md",
      "key": "v-553db0ed",
      "path": "/web/bw/",
      "headers": [
        {
          "level": 2,
          "title": "项目链接",
          "slug": "项目链接"
        },
        {
          "level": 2,
          "title": "框架架构图",
          "slug": "框架架构图"
        },
        {
          "level": 2,
          "title": "架构简介",
          "slug": "架构简介"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/web/ydxy/",
      "relativePath": "web/ydxy/README.md",
      "key": "v-a0de9366",
      "path": "/web/ydxy/",
      "headers": [
        {
          "level": 2,
          "title": "翔宇教育官网",
          "slug": "翔宇教育官网"
        },
        {
          "level": 2,
          "title": "翔宇教育管理端",
          "slug": "翔宇教育管理端"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebarDepth": 2,
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "前端项目",
        "link": "/web/"
      }
    ],
    "sidebar": [
      {
        "title": "云端学院",
        "path": "/web/ydxy/",
        "collapsable": false,
        "sidebarDepth": 1
      },
      {
        "title": "模拟教学",
        "path": "/web/mnjx/",
        "collapsable": false,
        "sidebarDepth": 1
      },
      {
        "title": "TRP航司合约标准版",
        "path": "/web/bw/",
        "children": []
      },
      {
        "title": "成航辅助营销管理端",
        "path": "/web/eu-fy/",
        "collapsable": false,
        "sidebarDepth": 1
      }
    ]
  }
}